### ISSUE TITLE
Usage of Auth Provider for Endpoint Authentications

### ISSUE THREAD

**Issue by kiritowu** [cliffchew84/SG-Lib-Books#166]
Current use of cookie as form of identification is vulnerable to impersonation. There is a need to use OAuth 2.0 process with Bearer JWT for endpoint authentication. Usage of Supabase Auth is required since supabase is already introduced into the stack.

**Comment by cliffchew84** [comment]
I was also looking at [https://auth0.com](https://auth0.com/pricing) as well, because it seems to have a higher volume for their free tier, but settled with Supabase first because I was already using it for our database. Feel free to explore what is comfortable for you.
