### ISSUE TITLE
Ambiguous date in Events section

### ISSUE THREAD

**Issue by elliotwutingfeng** [cliffchew84/SG-Lib-Books#83]
It is not clear if the date format is YYYY-MM-DD or YYYY-DD-MM.

**Comment by cliffchew84** [comment]
Noted on this. Let me add the comment on this soon

**Comment by cliffchew84** [comment]
Apologises, I forgot to create a branch from this issue to link the changes to this. Please refer to the latest pull request changes here https://github.com/cliffchew84/SG-Lib-Books/pull/88 I added comments on the date time format for the NLB Events in it latest commit.
